module.exports = function getData() {
    return [
        { id: 'Aquaman', name: 'AQUAMAN', information: 'Aquaman is a 2018 American superhero film based on the DC Comics character of the same name. Distributed by Warner Bros. Pictures, it is the sixth film in the DC Extended Universe (DCEU). The film was directed by James Wan, from a screenplay by David Leslie Johnson-McGoldrick and Will Beall and stars Jason Momoa as Aquaman, with Amber Heard, Willem Dafoe, Patrick Wilson, Dolph Lundgren, Yahya Abdul-Mateen II, and Nicole Kidman in supporting roles. In the film, Aquaman sets out to lead the underwater kingdom of Atlantis, replacing his half-brother, King Orm, who seeks to unite the seven underwater kingdoms against the surface world.' },
        { id: 'Avatar', name: 'AVATAR', information: `Avatar (marketed as James Cameron/'s Avatar is a 2009 American epic science fiction film directed, written, produced, and co-edited by James Cameron and stars Sam Worthington, Zoe Saldana, Stephen Lang, Michelle Rodriguez, and Sigourney Weaver. The film is set in the mid-22nd century when humans are colonizing Pandora, a lush habitable moon of a gas giant in the Alpha Centauri star system, in order to mine the mineral unobtanium, a room-temperature superconductor. The expansion of the mining colony threatens the continued existence of a local tribe of Na'vi – a humanoid species indigenous to Pandora. The film refers to a genetically engineered Na/'vi body operated from the brain of a remotely located human that is used to interact with the natives of Pandora.` },
        { id: 'el chapo', name: 'EL CHAPO', information: 'El Chapo è una serie televisiva statunitense co-prodotta da Univision e Netflix. La serie racconta la vita di Joaquín "El Chapo" Guzmán. È trasmessa dal 23 aprile 2017 sul canale Univision. A livello globale, la serie viene distribuita dal 16 giugno 2017 sul servizio on demand Netflix.' },
        { id: 'lord', name: 'Lord OF THE Rings', information: `The Lord of the Rings is an epic high-fantasy novel written by English author and scholar J. R. R. Tolkien. The story began as a sequel to Tolkien's 1937 fantasy novel The Hobbit, but eventually developed into a much larger work. Written in stages between 1937 and 1949, The Lord of the Rings is one of the best-selling novels ever written, with over 150 million copies sold` },
        { id: 'Black Panther', name: 'BLACK PANTHER', information: `Thousands of years ago, five African tribes war over a meteorite containing the metal vibranium. One warrior ingests a "heart-shaped herb" affected by the metal and gains superhuman abilities, becoming the first "Black Panther". He unites all but the Jabari Tribe to form the nation of Wakanda. Over centuries, the Wakandans use the vibranium to develop advanced technology and isolate themselves from the world by posing as a Third World country. In 1992, Wakanda's King T'Chaka visits his brother N'Jobu, who is working undercover in Oakland, California. T'Chaka accuses N'Jobu of assisting black-market arms dealer Ulysses Klaue with stealing vibranium from Wakanda. N'Jobu's partner reveals he is Zuri, another undercover Wakandan, and confirms T'Chaka's suspicions.`},
        { id: 'legend', name: 'I AM LEGEND', information: `I Am` }
    ]
} 